### ISSUE TITLE
The source of DeepColorization  

### ISSUE THREAD

**Issue by LinLeMon** [2014mchidamb/DeepColorization#1]
Hello,Mr Muthu. I am sorry to bother you. Would you please share the reference paper about DeepColorization  with me? Thank you so much.

**Comment by 2014mchidamb** [comment]
Hi, sorry - I've been meaning to update the readme with this information. The paper this is derived from is this: http://hi.cs.waseda.ac.jp/~iizuka/projects/colorization/en/

**Comment by LinLeMon** [comment]
Thank you very much!
